### ISSUE TITLE
I get this error in the example file.

### ISSUE THREAD

**Issue by sadysnaat** [GoesToEleven/GolangTraining#28]
After printing the string program panics and terminate. 

https://github.com/GoesToEleven/GolangTraining/blob/9e2be86862cd4243a87ce10a9cf4bd8e4d1f963a/21_interfaces/01_interface/05_io-copy/01_no-error-checking/main.go#L20

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11eb2f0]

goroutine 1 [running]:
main.main()
	<path>/main.go:21 +0x160
```

**Comment by sadysnaat** [comment]
Found the answer http://www.mcleods.com/ is unreachable. Hence closing it.

**Comment by phecht** [comment]
You should be able to change the website to one that works.

**Comment by jeremejazz** [comment]
pull request might be good
