### ISSUE TITLE
Cannot find list of packages

### ISSUE THREAD

**Issue by Dmdv** [GoesToEleven/GolangTraining#41]
"github.com/GoesToEleven/GolangTraining/47_templates/04_template_csv-parse/parse"
"github.com/GoesToEleven/GolangTraining/56_twitter/18_abstract-API-Model/api"
 "github.com/GoesToEleven/GolangTraining/56_twitter/19_abstract-API-Model_AE-fix/Model"
 "github.com/GoesToEleven/GolangTraining/56_twitter/19_abstract-API-Model_AE-fix/API"
"github.com/GoesToEleven/GolangTraining/56_twitter/19_abstract-API-Model_AE-fix/Memcache"

**Comment by HustYrf** [comment]
change to your local path

**Comment by KIMQI001** [comment]
hi
