### ISSUE TITLE
Add go vendor

### ISSUE THREAD

**Issue by farazfazli** [GoesToEleven/GolangTraining#9]
With Go 1.6 RC1 including vendor support without needing to set an extra environmental variable, I believe the concepts of vendoring should be introduced, as well as some demos with a popular go vendor tool like https://github.com/kardianos/govendor

Using a vendor tool flattens the dependency tree to a single level and allows for cleaner and more reliable code.

**Comment by shackra** [comment]
That would be great!

**Comment by GoesToEleven** [comment]
Thank you!

I will get to this as soon as possible.
